version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/install-meltingpot"
    schedule:
      interval: monthly

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/install-examples"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "vscode/devcontainers/python"
        versions: [">= 3.11"]
