defaults:
  - policy: ippo
  - env: simple_spread
  - buffer: default
  - runner: pgrunner

seed: 42
torch_deterministic: True
cuda: True
rollout_threads: 128
n_agents: 3
continuous_action: False
env_steps: 25
test_mode: False
latent_kl : False
use_policy_pool: False
experiment_name: test
hydra:
  run:
    dir: outputs/${experiment_name}