name: waterworld
family: sisl
rollout_threads: ${rollout_threads}
continuous_action: True
obs_type: vector
params: 
  n_pursuers: ${n_agents}
  n_evaders: 5
  n_poison: 10 
  n_coop: 2 
  n_sensors: 20
  sensor_range: 0.2
  radius: 0.015
  obstacle_radius: 0.2
  obstacle_coord: [0.5, 0.5]
  pursuer_max_accel: 0.01
  evader_speed: 0.01
  poison_speed: 0.01 
  poison_reward: -1.0 
  food_reward: 10.0 
  encounter_reward: 0.01
  thrust_penalty: -0.5
  local_ratio: 1.0 
  speed_features: True 
  max_cycles: ${env_steps}