from easydict import EasyDict as edict
config = edict()

config.SELFSUP_ATTENTION = edict()
config.SELFSUP_ATTENTION.NUM_KEYPOINTS = 10
config.SELFSUP_ATTENTION.GAUSS_STD = 0.11
config.SELFSUP_ATTENTION.AUTOENCODER_LOSS = False
config.SELFSUP_ATTENTION.KEYPOINTER_CLS_AGNOSTIC = False
config.SELFSUP_ATTENTION.HEATMAP_SPARSITY_LOSS = False
config.SELFSUP_ATTENTION.HEATMAP_SPARSITY_LOSS_WEIGHT = 0.
config.SELFSUP_ATTENTION.USE_LAYER_NORM = True
config.SELFSUP_ATTENTION.USE_INSTANCE_NORM = False
config.SELFSUP_ATTENTION.BLOCK_IMAGE_FEAT_GRADIENT = False
config.SELFSUP_ATTENTION.RECONSTRUCT_LOSS_THRESHOLD = 0.01
config.SELFSUP_ATTENTION.DECODER_WITH_SIGMOID = True
config.SELFSUP_ATTENTION.SHARE_PARAMETERS = False
